# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.DurationField(help_text='Enter Time required to complete the work')),
                ('description', models.TextField(blank=True, help_text='Enter description', max_length=2000, null=True)),
                ('perDone', models.IntegerField(default=0, help_text='Percentage remaining')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(help_text='Enter event name', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter event name', max_length=2000)),
                ('description', models.TextField(blank=True, help_text='Enter description', max_length=2000, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('totalTime', models.IntegerField(help_text='Enter Time required to complete the work')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter page name', max_length=2000)),
                ('description', models.TextField(blank=True, help_text='Enter description', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField(help_text='Enter your IITG roll No.')),
                ('key', models.TextField(blank=True, help_text='Enter page name', max_length=2000, null=True)),
                ('user', models.OneToOneField(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', related_name='my_pages', to='iitg.Student'),
        ),
        migrations.AddField(
            model_name='page',
            name='deadline',
            field=models.ManyToManyField(blank=True, help_text='Deadline of the page', null=True, to='iitg.Deadline'),
        ),
        migrations.AddField(
            model_name='page',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='iitg.Event'),
        ),
        migrations.AddField(
            model_name='page',
            name='students',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', related_name='subscribed_pages', to='iitg.Student'),
        ),
    ]
