# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='totalTime',
            field=models.IntegerField(help_text='Enter Time required in hours to complete the work'),
        ),
    ]
