# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0002_auto_20180929_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
